name = "Devicetree"
grammar = "devicetree"
path_suffixes = ["keymap", "overlay", "dts", "dtsi", "dtso", "its"]
line_comments = ["// "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "/*", end = " */", close = true, newline = false, not_in = ["string", "comment"] },
]
